services:
  spring-boot-observability:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-observability-container
    restart: always
    ports:
      - "31001:8080"
    environment:
      - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://<ALLOY_IP>:30006/v1/traces
      - LOKI_URL=http://<LOKI_IP>:30003/loki/api/v1/push