services:
  spring-boot-observability:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-observability-container
    restart: always
    ports:
      - "31001:8080"
    environment:
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://178.128.80.186:9411/api/v2/spans
      - LOKI_URL=http://178.128.80.186:3100/loki/api/v1/push