services:
  spring-boot-observability-altem:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-observability-altem
    restart: always
    ports:
      - "31001:8080"
    environment:
      - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://alloy-altem:4318/v1/traces
      - LOKI_URL=http://loki-altem:3100/loki/api/v1/push
    networks:
      - monitoring

networks:
  monitoring:
    external: true
    name: monitoring