services:
  spring-boot-observability-altem:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-observability-altem
    restart: always
    ports:
      - "31001:8080"
    environment:
      - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://178.128.80.186:30006/v1/traces
      - LOKI_URL=http://178.128.80.186:30003/loki/api/v1/push